#!/bin/bash

cd generator
java -jar generator.jar sample.mesh -mt irregular -np 2000 -lr 10

cd ../island
java -jar island.jar -i ../generator/sample.mesh -o island.mesh --mode lagoon

cd ../visualizer
java -jar visualizer.jar ../island/island.mesh sample.svg -T 2 -A 255
cd ..
